[package]
name = "neocmakelsp"
version = "0.8.19"
edition = "2024"
license = "MIT"
description = "The Lsp for cmake"
repository = "https://github.com/neocmakelsp/neocmakelsp"
authors = ["Decodertalkers <aakari@tutanota.com>"]
keywords = ["lsp"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.30", features = ["derive", "color"] }
tower-lsp = { version = "0.21.0", package = "tower-lsp-f" }
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.19"
tree-sitter = "0.25.2"
tree-sitter-cmake = "0.5.0"
regex = "1"
anyhow = "1.0.96"
cli-table = "0.4.9"
tracing = "0.1.41"
glob = "0.3.2"
rust-ini = "0.21.1"
ignore = "0.4.23"
toml = "0.8.20"
clap_complete = "4.5.45"
treesitter_kind_collector = "0.2.0"
anstyle = "1.0.10"
pathdiff = "0.2.3"

[target.'cfg(windows)'.dependencies]
path-absolutize = "3.1.1"

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }
tempfile = "3.17.1"

[profile.release]
lto = "thin"
